### ISSUE TITLE
compare with Werkzeug cache?

### ISSUE THREAD

**Issue by liuliqiang** [suzaku/cachelper#1]
hi suzaku, i'm happy to watch your code and docs, however i found this project is similar to [Werkzeug Cache](http://werkzeug.pocoo.org/docs/0.12/contrib/cache/), are there something difference or better than that?

**Comment by suzaku** [comment]
@yetship Thanks for paying attention to this project.

Like `werkzeug.contrib.cache`, this package aims to provide cache related utilities.
When I use `werkzeug.contrib.cache` in my Flask projects, I find it cumbersome to add caches to functions or methods and often implement helper functions to make my life easier with caches.
This package is a collection of such helpers.

It doesn't have to depend on `werkzeug` though, I'm working on providing my own basic cache classes to remove the only install requirement.
