### ISSUE TITLE
Missing text in README

### ISSUE THREAD

**Issue by DNSGeek** [suzaku/cachelper#3]
In the README, you state that you can use the @cache decorator on a function, but the example doesn't work:

>>> import cachelper
>>> @cache(key="key-{}".format('a'), timeout=300)
... def foo(a):
...  return('b')
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cache' is not defined

Additionally, you state that you can use 'cache.call' or cache.map' to cache functions when calling, if caching the entire function all the time is not practical, but that also doesn't work:

>>> import cachelper
>>> cache.call(lambda: foo('a'), 'key-a', timeout=300)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cache' is not defined

**Comment by suzaku** [comment]
Hi, those examples should be treated as code that appeared after the previous example, where `cache` is defined:

```python
from redis import StrictRedis
from werkzeug.contrib.cache import RedisCache as _RedisCache

from cachelper import HelperMixin

class RedisCache(_RedisCache, HelperMixin):
    '''werkzeug.contrib.cache.RedisCache mixed with HelperMixin'''

    def get_many(self, keys):
        return super().get_many(*keys)

rds = StrictRedis()
cache = RedisCache(rds)
```
